export enum AppRole {
  // ADMIN app roles
  SUPER_ADMIN = 'SUPER_ADMIN',

  // JRS app roles
  JRS_MEMBER = 'JRS_MEMBER',
  JRS_ADMIN = 'JRS_ADMIN',
  JRS_PC = 'JRS_PC',
  JRS_AP = 'JRS_AP',

  // FINANCE app roles
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  FINANCE_VIEWER = 'FINANCE_VIEWER',

  // CENTRE app roles
  CENTRE_CHEF = 'CENTRE_CHEF',
  COORDINATION = 'COORDINATION',
  INTENDANT = 'INTENDANT',
}
