export enum AppErrorCode {
  // Global Errors
  INTERNAL_SERVER_ERROR = 'GLOBAL_001',
  VALIDATION_FAILED = 'GLOBAL_002',

  // Auth Errors
  AUTH_UNAUTHORIZED = 'AUTH_001',
  AUTH_FORBIDDEN = 'AUTH_002',
  AUTH_EXPIRED_TOKEN = 'AUTH_003',
  AUTH_INVALID_CREDENTIALS = 'AUTH_004',
  ACCOUNT_NOT_ACTIVATED = 'AUTH_005',

  // Database Errors
  DB_ENTITY_NOT_FOUND = 'DB_001',
  DB_DUPLICATE_ENTRY = 'DB_002',
  DB_TRANSACTION_FAILED = 'DB_003',
}
